version: '3'
# 服务
services: 
  php_apache:
    # For single node
    # build: ./php_apache  # 镜像源

    # For swarm
    image: hmenv_php_apache
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    command: apache2-foreground  # bash 启动指令
    ports:
      - "80:80"  # 主机：容器端口的映射
    volumes:
      # VHost
      - ./php_apache/vhost/:/etc/apache2/sites-enabled/
      # - ./php_apache/vhost/fs2.com.conf:/etc/apache2/sites-enabled/fs2.com.conf
      # - ./php_apache/vhost/000-default.conf:/etc/apache2/sites-available/000-default.conf
      # Mount src dir
      - ./src:/var/www/html/fs2.com
      # Mount log files
      - ./php_apache/log:/var/log/fs2/
      # Mount php config
      - ./php_apache/my_php.ini:/usr/local/etc/php/conf.d/my_php.ini
    networks:
      - webnet

  mysql:
    image: mysql:latest   # 镜像源
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"  # 主机：容器端口的映射
    volumes:
      - ./data:/var/lib/mysql  # 数据存储位置的映射
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf    # 数据库配置文件
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # root无密码登陆
    networks:
      - webnet
networks:
  webnet:
